package com.xinyijia.backend.mapper;

import com.xinyijia.backend.domain.AttachmentInfo;
import com.xinyijia.backend.domain.AttachmentInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface AttachmentInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    int countByExample(AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    int deleteByExample(AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    int insert(AttachmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    int insertSelective(AttachmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    List<AttachmentInfo> selectByExample(AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    AttachmentInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    int updateByExampleSelective(@Param("record") AttachmentInfo record, @Param("example") AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    int updateByExample(@Param("record") AttachmentInfo record, @Param("example") AttachmentInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    int updateByPrimaryKeySelective(AttachmentInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment_info
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    int updateByPrimaryKey(AttachmentInfo record);
}