package com.xinyijia.backend.mapper;

import com.xinyijia.backend.domain.BusinessInfo;
import com.xinyijia.backend.domain.BusinessInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface BusinessInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    int countByExample(BusinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    int deleteByExample(BusinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    int insert(BusinessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    int insertSelective(BusinessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    List<BusinessInfo> selectByExample(BusinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    BusinessInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    int updateByExampleSelective(@Param("record") BusinessInfo record, @Param("example") BusinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    int updateByExample(@Param("record") BusinessInfo record, @Param("example") BusinessInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    int updateByPrimaryKeySelective(BusinessInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business_info
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    int updateByPrimaryKey(BusinessInfo record);
}