package com.xinyijia.backend.mapper;

import com.xinyijia.backend.domain.BuyCar;
import com.xinyijia.backend.domain.BuyCarExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface BuyCarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    int countByExample(BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    int deleteByExample(BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    int insert(BuyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    int insertSelective(BuyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    List<BuyCar> selectByExample(BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    BuyCar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    int updateByExampleSelective(@Param("record") BuyCar record, @Param("example") BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    int updateByExample(@Param("record") BuyCar record, @Param("example") BuyCarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    int updateByPrimaryKeySelective(BuyCar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table buy_car
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    int updateByPrimaryKey(BuyCar record);
}