package com.xinyijia.backend.mapper;

import com.xinyijia.backend.domain.NewsInfo;
import com.xinyijia.backend.domain.NewsInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface NewsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int countByExample(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int deleteByExample(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int insert(NewsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int insertSelective(NewsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    List<NewsInfo> selectByExampleWithBLOBs(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    List<NewsInfo> selectByExample(NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    NewsInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") NewsInfo record, @Param("example") NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") NewsInfo record, @Param("example") NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int updateByExample(@Param("record") NewsInfo record, @Param("example") NewsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int updateByPrimaryKeySelective(NewsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(NewsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_info
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    int updateByPrimaryKey(NewsInfo record);
}