package com.xinyijia.backend.mapper;

import com.xinyijia.backend.domain.TradeInfo;
import com.xinyijia.backend.domain.TradeInfoExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;

@Mapper
@Component
public interface TradeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    int countByExample(TradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    int deleteByExample(TradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    int insert(TradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    int insertSelective(TradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    List<TradeInfo> selectByExample(TradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    TradeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    int updateByExampleSelective(@Param("record") TradeInfo record, @Param("example") TradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    int updateByExample(@Param("record") TradeInfo record, @Param("example") TradeInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    int updateByPrimaryKeySelective(TradeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_info
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    int updateByPrimaryKey(TradeInfo record);
}