package com.xinyijia.backend.domain;

public class AttachmentInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_info.id
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_info.file_name
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_info.file_type
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_info.file_size
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    private String fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_info.file_address
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    private String fileAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_info.create_time
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_info.category
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_info.file_desc
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    private String fileDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment_info.old_name
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    private String oldName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_info.id
     *
     * @return the value of attachment_info.id
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_info.id
     *
     * @param id the value for attachment_info.id
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_info.file_name
     *
     * @return the value of attachment_info.file_name
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_info.file_name
     *
     * @param fileName the value for attachment_info.file_name
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_info.file_type
     *
     * @return the value of attachment_info.file_type
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_info.file_type
     *
     * @param fileType the value for attachment_info.file_type
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_info.file_size
     *
     * @return the value of attachment_info.file_size
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public String getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_info.file_size
     *
     * @param fileSize the value for attachment_info.file_size
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public void setFileSize(String fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_info.file_address
     *
     * @return the value of attachment_info.file_address
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public String getFileAddress() {
        return fileAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_info.file_address
     *
     * @param fileAddress the value for attachment_info.file_address
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public void setFileAddress(String fileAddress) {
        this.fileAddress = fileAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_info.create_time
     *
     * @return the value of attachment_info.create_time
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_info.create_time
     *
     * @param createTime the value for attachment_info.create_time
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_info.category
     *
     * @return the value of attachment_info.category
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_info.category
     *
     * @param category the value for attachment_info.category
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_info.file_desc
     *
     * @return the value of attachment_info.file_desc
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public String getFileDesc() {
        return fileDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_info.file_desc
     *
     * @param fileDesc the value for attachment_info.file_desc
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public void setFileDesc(String fileDesc) {
        this.fileDesc = fileDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment_info.old_name
     *
     * @return the value of attachment_info.old_name
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public String getOldName() {
        return oldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment_info.old_name
     *
     * @param oldName the value for attachment_info.old_name
     *
     * @mbggenerated Sat May 19 21:42:49 CST 2018
     */
    public void setOldName(String oldName) {
        this.oldName = oldName;
    }
}