package com.xinyijia.backend.domain;

public class BusinessInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.id
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.business_name
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.business_desc
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    private String businessDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business_info.principal_owner
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    private String principalOwner;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.id
     *
     * @return the value of business_info.id
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.id
     *
     * @param id the value for business_info.id
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.business_name
     *
     * @return the value of business_info.business_name
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    public String getBusinessName() {
        return businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.business_name
     *
     * @param businessName the value for business_info.business_name
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    public void setBusinessName(String businessName) {
        this.businessName = businessName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.business_desc
     *
     * @return the value of business_info.business_desc
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    public String getBusinessDesc() {
        return businessDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.business_desc
     *
     * @param businessDesc the value for business_info.business_desc
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    public void setBusinessDesc(String businessDesc) {
        this.businessDesc = businessDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business_info.principal_owner
     *
     * @return the value of business_info.principal_owner
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    public String getPrincipalOwner() {
        return principalOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business_info.principal_owner
     *
     * @param principalOwner the value for business_info.principal_owner
     *
     * @mbggenerated Wed May 16 21:29:38 CST 2018
     */
    public void setPrincipalOwner(String principalOwner) {
        this.principalOwner = principalOwner;
    }
}