package com.xinyijia.backend.domain;

public class BuyCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.id
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.quantity
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.price
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.user_id
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column buy_car.product_id
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    private Integer productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.id
     *
     * @return the value of buy_car.id
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.id
     *
     * @param id the value for buy_car.id
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.quantity
     *
     * @return the value of buy_car.quantity
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.quantity
     *
     * @param quantity the value for buy_car.quantity
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.price
     *
     * @return the value of buy_car.price
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.price
     *
     * @param price the value for buy_car.price
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.user_id
     *
     * @return the value of buy_car.user_id
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.user_id
     *
     * @param userId the value for buy_car.user_id
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column buy_car.product_id
     *
     * @return the value of buy_car.product_id
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column buy_car.product_id
     *
     * @param productId the value for buy_car.product_id
     *
     * @mbggenerated Fri May 18 22:37:37 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
}