package com.xinyijia.backend.domain;

public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.id
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.company_tel
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String companyTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.company_address
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.company_phone
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String companyPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.email
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.email_code
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String emailCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.create_time
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.fax
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String fax;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.size
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String size;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.web_site
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String webSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.recruit_id
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private Integer recruitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.about_id
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private Integer aboutId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.company_name
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.company_desc
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    private String companyDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.id
     *
     * @return the value of company_info.id
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.id
     *
     * @param id the value for company_info.id
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.company_tel
     *
     * @return the value of company_info.company_tel
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getCompanyTel() {
        return companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.company_tel
     *
     * @param companyTel the value for company_info.company_tel
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setCompanyTel(String companyTel) {
        this.companyTel = companyTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.company_address
     *
     * @return the value of company_info.company_address
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.company_address
     *
     * @param companyAddress the value for company_info.company_address
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.company_phone
     *
     * @return the value of company_info.company_phone
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getCompanyPhone() {
        return companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.company_phone
     *
     * @param companyPhone the value for company_info.company_phone
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setCompanyPhone(String companyPhone) {
        this.companyPhone = companyPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.email
     *
     * @return the value of company_info.email
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.email
     *
     * @param email the value for company_info.email
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.email_code
     *
     * @return the value of company_info.email_code
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getEmailCode() {
        return emailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.email_code
     *
     * @param emailCode the value for company_info.email_code
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setEmailCode(String emailCode) {
        this.emailCode = emailCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.create_time
     *
     * @return the value of company_info.create_time
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.create_time
     *
     * @param createTime the value for company_info.create_time
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.fax
     *
     * @return the value of company_info.fax
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getFax() {
        return fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.fax
     *
     * @param fax the value for company_info.fax
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setFax(String fax) {
        this.fax = fax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.size
     *
     * @return the value of company_info.size
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.size
     *
     * @param size the value for company_info.size
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.web_site
     *
     * @return the value of company_info.web_site
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getWebSite() {
        return webSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.web_site
     *
     * @param webSite the value for company_info.web_site
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setWebSite(String webSite) {
        this.webSite = webSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.recruit_id
     *
     * @return the value of company_info.recruit_id
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public Integer getRecruitId() {
        return recruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.recruit_id
     *
     * @param recruitId the value for company_info.recruit_id
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setRecruitId(Integer recruitId) {
        this.recruitId = recruitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.about_id
     *
     * @return the value of company_info.about_id
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public Integer getAboutId() {
        return aboutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.about_id
     *
     * @param aboutId the value for company_info.about_id
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setAboutId(Integer aboutId) {
        this.aboutId = aboutId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.company_name
     *
     * @return the value of company_info.company_name
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.company_name
     *
     * @param companyName the value for company_info.company_name
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.company_desc
     *
     * @return the value of company_info.company_desc
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public String getCompanyDesc() {
        return companyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.company_desc
     *
     * @param companyDesc the value for company_info.company_desc
     *
     * @mbggenerated Sun May 20 00:15:43 CST 2018
     */
    public void setCompanyDesc(String companyDesc) {
        this.companyDesc = companyDesc;
    }
}