package com.xinyijia.backend.domain;

public class NewsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.id
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.type
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.category
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.title
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.title_image
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    private String titleImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.author
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.publish_time
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    private Long publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_info.content
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.id
     *
     * @return the value of news_info.id
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.id
     *
     * @param id the value for news_info.id
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.type
     *
     * @return the value of news_info.type
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.type
     *
     * @param type the value for news_info.type
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.category
     *
     * @return the value of news_info.category
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.category
     *
     * @param category the value for news_info.category
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.title
     *
     * @return the value of news_info.title
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.title
     *
     * @param title the value for news_info.title
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.title_image
     *
     * @return the value of news_info.title_image
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public String getTitleImage() {
        return titleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.title_image
     *
     * @param titleImage the value for news_info.title_image
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public void setTitleImage(String titleImage) {
        this.titleImage = titleImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.author
     *
     * @return the value of news_info.author
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.author
     *
     * @param author the value for news_info.author
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.publish_time
     *
     * @return the value of news_info.publish_time
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public Long getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.publish_time
     *
     * @param publishTime the value for news_info.publish_time
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public void setPublishTime(Long publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_info.content
     *
     * @return the value of news_info.content
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_info.content
     *
     * @param content the value for news_info.content
     *
     * @mbggenerated Thu May 17 19:43:18 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}