package com.xinyijia.backend.domain;

public class ProductInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.id
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.category
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.price
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.image_name
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String imageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_desc
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.business_id
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_time
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.search_index
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String searchIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.quantity
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.selling
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Integer selling;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.id
     *
     * @return the value of product_info.id
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.id
     *
     * @param id the value for product_info.id
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_name
     *
     * @return the value of product_info.product_name
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_name
     *
     * @param productName the value for product_info.product_name
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.category
     *
     * @return the value of product_info.category
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.category
     *
     * @param category the value for product_info.category
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.price
     *
     * @return the value of product_info.price
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.price
     *
     * @param price the value for product_info.price
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.image_name
     *
     * @return the value of product_info.image_name
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.image_name
     *
     * @param imageName the value for product_info.image_name
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.product_desc
     *
     * @return the value of product_info.product_desc
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public String getProductDesc() {
        return productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.product_desc
     *
     * @param productDesc the value for product_info.product_desc
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setProductDesc(String productDesc) {
        this.productDesc = productDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.business_id
     *
     * @return the value of product_info.business_id
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.business_id
     *
     * @param businessId the value for product_info.business_id
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.create_time
     *
     * @return the value of product_info.create_time
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.create_time
     *
     * @param createTime the value for product_info.create_time
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.update_time
     *
     * @return the value of product_info.update_time
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.update_time
     *
     * @param updateTime the value for product_info.update_time
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.search_index
     *
     * @return the value of product_info.search_index
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public String getSearchIndex() {
        return searchIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.search_index
     *
     * @param searchIndex the value for product_info.search_index
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setSearchIndex(String searchIndex) {
        this.searchIndex = searchIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.quantity
     *
     * @return the value of product_info.quantity
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.quantity
     *
     * @param quantity the value for product_info.quantity
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product_info.selling
     *
     * @return the value of product_info.selling
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public Integer getSelling() {
        return selling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product_info.selling
     *
     * @param selling the value for product_info.selling
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    public void setSelling(Integer selling) {
        this.selling = selling;
    }
}