package com.xinyijia.backend.domain;

public class TradeInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.id
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.user_id
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.product_id
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    private Integer productId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.quantity
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.price
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.createTime
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    private Long createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.updateTime
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    private Long updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.id
     *
     * @return the value of trade_info.id
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.id
     *
     * @param id the value for trade_info.id
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.user_id
     *
     * @return the value of trade_info.user_id
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.user_id
     *
     * @param userId the value for trade_info.user_id
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.product_id
     *
     * @return the value of trade_info.product_id
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.product_id
     *
     * @param productId the value for trade_info.product_id
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.quantity
     *
     * @return the value of trade_info.quantity
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public Integer getQuantity() {
        return quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.quantity
     *
     * @param quantity the value for trade_info.quantity
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.price
     *
     * @return the value of trade_info.price
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.price
     *
     * @param price the value for trade_info.price
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.createTime
     *
     * @return the value of trade_info.createTime
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public Long getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.createTime
     *
     * @param createtime the value for trade_info.createTime
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public void setCreatetime(Long createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.updateTime
     *
     * @return the value of trade_info.updateTime
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public Long getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.updateTime
     *
     * @param updatetime the value for trade_info.updateTime
     *
     * @mbggenerated Fri May 18 20:48:23 CST 2018
     */
    public void setUpdatetime(Long updatetime) {
        this.updatetime = updatetime;
    }
}