package com.xinyijia.backend.domain;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.category
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.user_name
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.tel_num
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String telNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.id_card
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.address
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.image_icon
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String imageIcon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.balance
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private Long balance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.buyCar_id
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private Integer buycarId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.create_time
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.sex
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birthday
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.age
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.view_products
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    private String viewProducts;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id
     *
     * @return the value of user_info.id
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id
     *
     * @param id the value for user_info.id
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.category
     *
     * @return the value of user_info.category
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.category
     *
     * @param category the value for user_info.category
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.user_name
     *
     * @return the value of user_info.user_name
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.user_name
     *
     * @param userName the value for user_info.user_name
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.tel_num
     *
     * @return the value of user_info.tel_num
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getTelNum() {
        return telNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.tel_num
     *
     * @param telNum the value for user_info.tel_num
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setTelNum(String telNum) {
        this.telNum = telNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.id_card
     *
     * @return the value of user_info.id_card
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.id_card
     *
     * @param idCard the value for user_info.id_card
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.address
     *
     * @return the value of user_info.address
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.address
     *
     * @param address the value for user_info.address
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.image_icon
     *
     * @return the value of user_info.image_icon
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getImageIcon() {
        return imageIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.image_icon
     *
     * @param imageIcon the value for user_info.image_icon
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setImageIcon(String imageIcon) {
        this.imageIcon = imageIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.balance
     *
     * @return the value of user_info.balance
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public Long getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.balance
     *
     * @param balance the value for user_info.balance
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setBalance(Long balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.buyCar_id
     *
     * @return the value of user_info.buyCar_id
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public Integer getBuycarId() {
        return buycarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.buyCar_id
     *
     * @param buycarId the value for user_info.buyCar_id
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setBuycarId(Integer buycarId) {
        this.buycarId = buycarId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.create_time
     *
     * @return the value of user_info.create_time
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.create_time
     *
     * @param createTime the value for user_info.create_time
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.sex
     *
     * @return the value of user_info.sex
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.sex
     *
     * @param sex the value for user_info.sex
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birthday
     *
     * @return the value of user_info.birthday
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birthday
     *
     * @param birthday the value for user_info.birthday
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.age
     *
     * @return the value of user_info.age
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.age
     *
     * @param age the value for user_info.age
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.view_products
     *
     * @return the value of user_info.view_products
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public String getViewProducts() {
        return viewProducts;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.view_products
     *
     * @param viewProducts the value for user_info.view_products
     *
     * @mbggenerated Tue May 15 14:15:59 CST 2018
     */
    public void setViewProducts(String viewProducts) {
        this.viewProducts = viewProducts;
    }
}