package com.xinyijia.backend.param;

import lombok.Data;

/**
 * @author tanjia
 * @email 378097217@qq.com
 * @date 2018/5/17 14:07
 */
@Data
public class ProductResponse {

    private String imageUrl;

    private String businessName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.id
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_name
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String productName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.category
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String category;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.price
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Integer price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.image_name
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String imageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.product_desc
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String productDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.business_id
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Integer businessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.create_time
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Long createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.update_time
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Long updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.search_index
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private String searchIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.quantity
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private Integer quantity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product_info.selling
     *
     * @mbggenerated Wed May 16 17:41:15 CST 2018
     */
    private boolean selling;

    private Long sellNum;

}
